title: <p align="center"> Sebastian Oliva </p>

description:
  
  <p align="justify">
  Estudiante de Ingeniería Civil Eléctrica en Universidad de La Frontera, Chile.
  <br><br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
